### ISSUE TITLE
Dtc Service [MW]

### ISSUE THREAD

**Issue by bartoszsnieg** [Simba-Avionic/srp#1]
- [x] Dokumentacja
- [ ] Implementacja serwisu:
  - [x] implementacja DTC callback
  - [ ] implementacja diag callback
- [x] Sterowniki dla klientów

**Comment by Mateusz-Krajewski** [comment]
zablokowane przez :https://github.com/orgs/Simba-Avionic/projects/7?pane=issue&itemId=49004339

**Comment by bartoszsnieg** [comment]
@Mateusz-Krajewski  jakies postepy ?

**Comment by Mateusz-Krajewski** [comment]
> @Mateusz-Krajewski jakies postepy ?

nie, ale jeśli pamiętam trzeba doimplementować diagnostyke, i kilka poprawek zostało.

**Comment by Mateusz-Krajewski** [comment]
> @Mateusz-Krajewski jakies postepy ?



> @Mateusz-Krajewski jakies postepy ?

zmiany są na masterze, issue się nie zamknoł, mieliśmy rozpisać osobnego taska na implementacje met. diagnostycznych
