### ISSUE TITLE
Parser Json

### ISSUE THREAD

**Issue by Mateusz-Krajewski** [Simba-Avionic/srp#11]

**Comment by Mateusz-Krajewski** [comment]
Jak postępy?

**Comment by StridingMerchant** [comment]
> Jak postępy?

W ten weekend podziałam, dzisiaj 4ty kolos od nowego roku

**Comment by Mateusz-Krajewski** [comment]
nastąpiły drobne zmiany w pliku który masz wczytywać, tutaj najnowsza wersja

![Image](https://github.com/Simba-Avionic/srp/assets/59980471/7d2be389-c4c4-4bfd-9ce0-7cc0080a13ae)
