### ISSUE TITLE
Create I2C driver

### ISSUE THREAD

**Issue by Mateusz-Krajewski** [Simba-Avionic/srp#14]
TODO
- [ ] Co to I2C
- [ ] Jak działa I2C
- [ ] Jak korzystać z I2C na Rpi4 lub beaglebone bez korzystania zewnętrznych bibliotek
- [ ] stworzenie interfejsu dla biblioteki I2C
- [ ] zaimplementowanie biblioteki I2C

BACKLOG
- [ ] Wymyślić emulowanie czujników po i2c

Przydatne linki:
- https://medium.com/geekculture/raspberry-pi-c-libraries-for-working-with-i2c-spi-and-uart-4677f401b584
- https://stackoverflow.com/questions/22611675/i-am-trying-to-use-i2c-on-the-beagle-bone-black-with-c-but-i-keep-getting-0x00
- https://pl.wikipedia.org/wiki/I%C2%B2C

**Comment by bartoszsnieg** [comment]
example https://github.com/shenki/linux-i2c-example/blob/master/i2c_example.c

**Comment by Mateusz-Krajewski** [comment]
srp/core/i2c_driver
