### ISSUE TITLE
Config Generator ignore method client in db section

### ISSUE THREAD

**Issue by Mateusz-Krajewski** [Simba-Avionic/srp#63]
Jeśli klient  jest na tym samym komputerze co server, config parser nie dodaje jego adresu do sekcji db pliku app_someip.json.
Problem nie występuje jeśli klient i server są na różnych komputerach.
[branch z zaobserwowanym problemem](https://github.com/Simba-Avionic/srp/tree/makr_primer_service)

brakuje serwisu o id 15
![image](https://github.com/Simba-Avionic/srp/assets/59980471/d4b64fe9-a281-47bf-b031-b1dbb83bebfc)
![image](https://github.com/Simba-Avionic/srp/assets/59980471/9cff26d3-b271-42b1-abea-e98792ead169)
[log.zip](https://github.com/Simba-Avionic/srp/files/15053052/log.zip)

**Comment by bartoszsnieg** [comment]
Widze że App ID dałeś o jeden znak za długi

**Comment by bartoszsnieg** [comment]
Po rzeanalizowaniu problemu uważam ze bła jest w skrypcie od generowania plików konfiguracyjnych. Problem rozwiązany będzie wraz z wprowadzeniem wersji 1.5 (Access list)

**Comment by bartoszsnieg** [comment]
Ale cały nie powiem dlt logi to cos zajebistego w naszym przypadku ps. nawet sentinel tego nie ma ;)

**Comment by Mateusz-Krajewski** [comment]
> Ale nie powiem dlt logi to cos zajebistego w naszym przypadku ps. nawet sentinel tego nie ma ;)

tak, mega ułatwia prace
