### ISSUE TITLE
nlohmann_json drop app if input file is not a valid json

### ISSUE THREAD

**Issue by Mateusz-Krajewski** [Simba-Avionic/srp#98]
przed nlohmann::json::parse(file);
trzeba sprawdzać poprawność json.
nlohmann::json udostępnia metode accept która zwraca czy jest to poprawny json, jednak nie można do niej przekazać pliku gdyż json::parse nie wczyta potem z niego danych, chyba że da się jakoś zresetować wskaźnik w pliku.

![att vxFFPWcXK-1b4-6TpDUFT5X25FVXkHa5sPpvBWCaTYg](https://github.com/Simba-Avionic/srp/assets/59980471/2b461039-c24b-45cc-bd15-4b29527b2686)

do poprawy są wszystkie aplikacje wczytujące dane z pliku json i json_parser

- [ ] stworzenie klasy która wczyta dane z pliku o zadanej ścieżce
- [ ] stworzenie parsera json który zwróci optional<nlohmann::json>
- [ ] poprawa bierzących aplikacji

**Comment by bartoszsnieg** [comment]
to można by przejść na jakąś warstwe abstrakcji żeby się przed tym zabezpieczyć . Przynajmniej fabryke trzeb aby było zrobić która będzie zwracać zwalidowany plik lub nie

**Comment by Mateusz-Krajewski** [comment]
+trzeba zrobić abstrakcje dla oczytu z pliku żeby się to zmockować dało

**Comment by bartoszsnieg** [comment]
Niekoniecznie abstrakcja jest konieczna. Da się to inaczej też ogarnąć

**Comment by Mateusz-Krajewski** [comment]
@bartoszsnieg  jak?
